name: Public Releases
on:
  workflow_run:
    workflows: build
    types: completed
  workflow_dispatch:

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          repository: Solara-Energias/solara-admin-app-releases
          token: ${{ secrets.GITHUB_TOKEN }}
